# Generated by Django 4.2.5 on 2023-10-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
