# Generated by Django 4.2.5 on 2023-10-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dividend_date_alter_dividend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
